language: python
python:
    - "2.7"
install:
    - pip install --allow-external jianfan --allow-unverified jianfan -r requirements.txt
    - pip install coveralls
    - mkdir test_preprocessed
    - mkdir test_output
    - ls
script:
    - nosetests
    - coverage run --source=preprocessing,processing,models,postprocessing,utilities run_tests.py
after_success:
    - coveralls
branches:
    only:
        - master
        - develop
        - /^travis.*$/
sudo: false
