language: python
python:
    - "2.7"
install:
    - pip install -r requirements.txt
    - pip install coveralls
    - mkdir test_preprocessed
    - mkdir test_output
script:
    - nosetests
    - coverage run run_tests.py
after_success:
    - coveralls
branches:
    only:
        - master
        - develop

